grub install improvements, keep syslinux if available (fehlix)

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -8,8 +8,8 @@
 # License: GPLv3 or later
 #==============================================================================
 
-      VERSION="2.41.24"
- VERSION_DATE="Sat, 04 Apr 2026"
+      VERSION="2.41.26"
+ VERSION_DATE="Sat, 09 Apr 2026"
 
         ME=${0##*/}
     MY_DIR=$(dirname "$(readlink -f $0)")
@@ -1008,7 +1008,7 @@ main() {
     [ ${#cheats} -gt 0 ] && need cheats-syslinux && do_cheats_syslinux $BIOS_DIR "$cheats"
     [ ${#cheats} -gt 0 ] && need cheats-grub     && do_cheats_grub     $UEFI_DIR "$cheats"
 
-    need install $"install" && do_install_bootloader $target_dev $BIOS_DIR $MSDOS_GPT
+    need install $"install" && do_install_bootloader $target_dev $BIOS_DEV $BIOS_DIR $MSDOS_GPT $ISO_DIR
 
     sync; sync
 
@@ -1604,11 +1604,27 @@ setup_devices() {
 
     if encrypt; then
         local bios_part=1  main_part=2  ;  UEFI_PART=3
-
+        # bios_grub partition
+        BGRP_PART=
+        if [ "$MSDOS_GPT" = "gpt" ] && [ "$GRUB_MBR" = "true" ]; then
+            BGRP_PART=1
+            bios_part=2
+            main_part=3
+            UEFI_PART=4
+            BGRP_DEV=$(get_partition $drive $BGRP_PART)
+        fi
         if data_first; then
             bios_part=2
             main_part=3
             UEFI_PART=4
+
+            if [ "$MSDOS_GPT" = "gpt" ] && [ "$GRUB_MBR" = "true" ]; then
+                BGRP_PART=2
+                bios_part=3
+                main_part=4
+                UEFI_PART=5
+                BGRP_DEV=$(get_partition $drive $BGRP_PART)
+            fi
             DATA_DEV=$(get_partition $drive 1)
         fi
 
@@ -1622,10 +1638,25 @@ setup_devices() {
 
     else
         local main_part=1 ; UEFI_PART=2
+        # bios_grub partition
+        BGRP_PART=
+        if [ "$MSDOS_GPT" = "gpt" ] && [ "$GRUB_MBR" = "true" ]; then
+            BGRP_PART=1
+            main_part=2
+            UEFI_PART=3
+            BGRP_DEV=$(get_partition $drive $BGRP_PART)
+        fi
 
         if data_first; then
             main_part=2
             UEFI_PART=3
+
+            if [ "$MSDOS_GPT" = "gpt" ] && [ "$GRUB_MBR" = "true" ]; then
+                BGRP_PART=2
+                main_part=3
+                UEFI_PART=4
+                BGRP_DEV=$(get_partition $drive $BGRP_PART)
+            fi
             DATA_DEV=$(get_partition $drive 1)
         fi
 
@@ -2098,7 +2129,9 @@ do_partition() {
     local PREAMB="parted --script --align optimal $dev unit MiB"
     cmd $PREAMB mklabel $type || dmesg_fatal "$err_msg" making partition
 
-    local START=1  PART_NUM=0  main_fs=ext4
+    local START=1  PART_NUM=0
+
+    local main_fs=ext4
 
     if data_first; then
         local total_size=$TOTAL_SIZE
@@ -2127,11 +2160,21 @@ do_partition() {
 	    fi     
     fi
     
+
+    if [ "$type" = "gpt" ] && [ "$GRUB_MBR" = "true" ]; then
+        # bios_grub
+        local bios_grub_size=2
+        _add_partition "$bios_grub_size" ""  "bios_grub"
+        mark="bios_grub"
+	    cmd $PREAMB set $PART_NUM $mark on || dmesg_fatal "$err_msg" esp-flag
+    fi
+
     if [ $bios_size -gt 0 ]; then
         _add_partition $bios_size bios
         cmd $PREAMB set $PART_NUM $boot_flag on || dmesg_fatal "$err_msg" boot-flag-1
         main_fs=
     fi
+ 
     _add_partition "$main_size" $main_fs  main
     if ! encrypt; then
         cmd $PREAMB set $PART_NUM $boot_flag on || dmesg_fatal "$err_msg" boot-flag-2
@@ -2162,6 +2205,7 @@ _add_partition() {
         ext[234]) part_fstype=$fstype ;;
             vfat) part_fstype=fat32   ;;
             ntfs) part_fstype=NTFS    ;;
+            none) part_fstype=none    ;;
     esac
 
     clear_filesystem $dev $START
@@ -2672,12 +2716,7 @@ random_string() {
 # This installs the legacy syslinux bootloader
 #------------------------------------------------------------------------------
 do_install_bootloader() {
-    if [[ "$GRUB_MBR" = "true" ]]; then
-        do_install_bootloader_grub "$@"
-        return
-    fi
-
-    local dev=$1  bios_dir=$2  type=$3
+    local dev=$1 bios_dev=$2  bios_dir=$3  type=$4 type iso_dir=$5
 
     msg "extlinux version %s" "$(pq $(get_extlinux_version))"
 
@@ -2735,25 +2774,85 @@ do_install_bootloader() {
      # [don't translate syslinux or isolinux]
     [ -z "$syslinux_dir" ] && fatal "Could not find a syslinux or isolinux directory"
 
-    cmd extlinux -i $syslinux_dir || fatal "%s command failed" extlinux
+    cmd extlinux -i --device="$bios_dev" $syslinux_dir || fatal "%s command failed" extlinux
+
+    if [ "$GRUB_MBR" = "true" ]; then
+        do_install_bootloader_grub "$dev" "$bios_dir" "$type" "$iso_dir"
+    fi
+
 }
 
 do_install_bootloader_grub() {
     local dev=$1        # Target device (e.g., /dev/sda)
     local bios_dir=$2   # Mount point of the boot partition
     local type=$3       # Partition scheme (gpt or msdos)
+    local iso_dir=$4    # Mount point of the iso loop-device
 
+    local grub_dir
+    if [ -d "$iso_dir/boot/grub/i386-pc" ]; then
+        grub_dir="$iso_dir/boot/grub/i386-pc"
+    else
+        grub_dir="/usr/lib/grub/i386-pc"
+    fi
+    
     msg "Installing GRUB2 for %s partitioning on %s" "$type" "$dev"
 
     # 1. Install GRUB2 to the MBR of the target device
     # --target=i386-pc is the standard for legacy BIOS/MBR systems
     # --boot-directory tells GRUB where /boot is
     # not making a new grub.cfg file since its a live system
-    cmd grub-install --target=i386-pc --boot-directory="$bios_dir/boot" "$dev" \
+    cmd grub-install --target=i386-pc --boot-directory="$bios_dir/boot" \
+        --fonts= \
+        --locales= \
+        --themes= \
+        --directory="$grub_dir" \
+        "$dev" \
         || fatal "grub-install failed on %s" "$dev"
+        
+    # remove empty locale-dir created by grub-install
+    if [ -d "$bios_dir/boot/grub/locale/" ]; then
+        cmd rm -r "$bios_dir/boot/grub/locale/"
+    fi
+    # restore unicode font from iso
+    if [ -f "$iso_dir/boot/grub/fonts/unicode.pf2" ]; then
+        cmd cp "$iso_dir/boot/grub/fonts/unicode.pf2" "$bios_dir/boot/grub/fonts/"
+    fi
+    
+    # restore core.img and eltorito.img from iso
+    if [ -f "$iso_dir/boot/grub/i386-pc/core.img" ]; then
+        cmd cp "$iso_dir/boot/grub/i386-pc/core.img" "$bios_dir/boot/grub/i386-pc/"
+    fi
+    if [ -f "$iso_dir/boot/grub/i386-pc/eltorito.img" ]; then
+        cmd cp "$iso_dir/boot/grub/i386-pc/eltorito.img" "$bios_dir/boot/grub/i386-pc/"
+    fi
 
-   #comment out syslinux menus
-   sed -i '/^[^#]*switch_to_syslinux/s/^/#/' $bios_dir/boot/grub/config/bootmenu.cfg
+    # restore lnxboot.img from iso or installed grub
+    if ! [ -f "$bios_dir/boot/grub/i386-pc/lnxboot.img" ]; then
+
+        if [ -f "$iso_dir/boot/grub/i386-pc/lnxboot.img" ]; then
+            cmd cp "$iso_dir/boot/grub/i386-pc/lnxboot.img" "$bios_dir/boot/grub/i386-pc/"
+
+        elif [ -f "/usr/lib/grub/i386-pc/lnxboot.img" ]; then
+            cmd cp "/usr/lib/grub/i386-pc/lnxboot.img" "$bios_dir/boot/grub/i386-pc/"
+        fi
+    fi
+    
+    # restore syslinux.bin from iso 
+    if [ ! -f "$bios_dir/boot/syslinux/syslinux.bin" ] && [ -d "$bios_dir/boot/syslinux/" ]; then
+        if [ -f "$iso_dir/boot/syslinux/syslinux.bin" ]; then
+            cmd cp "$iso_dir/boot/syslinux/syslinux.bin" "$bios_dir/boot/syslinux/"
+        elif [ -f "$iso_dir/boot/isolinux/isolinux.bin" ]; then
+            cmd cp "$iso_dir/boot/isolinux/isolinux.bin" "$bios_dir/boot/syslinux/syslinux.bin"
+        fi
+    fi
+
+    if [ -f "$bios_dir/boot/grub/i386-pc/lnxboot.img" ]; then
+       # re-enable syslinux menus
+       sed -i -r 's/^([#[:space:]]+)(switch_to_syslinux)/\2/' "$bios_dir/boot/grub/config/bootmenu.cfg"
+    else
+       #comment out syslinux menus
+       sed -i '/^[^#]*switch_to_syslinux/s/^/#/' "$bios_dir/boot/grub/config/bootmenu.cfg"
+    fi
     msg "GRUB2 installation complete."
 }
 
